"""add bio and profile_pic to user

Revision ID: 0fd05bfa8833
Revises: a6c3e592eff1
Create Date: 2025-07-22 18:41:58.833582

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0fd05bfa8833"
down_revision = "a6c3e592eff1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bio", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("profile_pic", sa.String(length=256), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("profile_pic")
        batch_op.drop_column("bio")

    # ### end Alembic commands ###
