"""Add pseudo field to user

Revision ID: a6c3e592eff1
Revises: d954849e7ee9
Create Date: 2025-07-22 17:58:30.603454

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6c3e592eff1"
down_revision = "d954849e7ee9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pseudo", sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(
            "uq_users_pseudo", ["pseudo"]
        )  # <-- name added here!
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_users_pseudo", type_="unique"
        )  # <-- name added here!
        batch_op.drop_column("pseudo")
    # ### end Alembic commands ###
