"""Make sender_id and receiver_id nullable

Revision ID: c7b48ea44ea7
Revises: f2e31550a5d9
Create Date: 2025-07-27 19:02:25.013903
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b48ea44ea7'
down_revision = 'f2e31550a5d9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        # Skip the drop_constraint if it doesn't exist
        batch_op.create_foreign_key('messages_receiver_id_fkey', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('messages_sender_id_fkey', 'users', ['sender_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###

def downgrade():
    # ### downgrade script - undo changes ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        # Drop the newly created foreign keys
        batch_op.drop_constraint('messages_receiver_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('messages_sender_id_fkey', type_='foreignkey')
        
        # Recreate original foreign keys without CASCADE
        batch_op.create_foreign_key('messages_receiver_id_fkey', 'users', ['receiver_id'], ['id'])
        batch_op.create_foreign_key('messages_sender_id_fkey', 'users', ['sender_id'], ['id'])

    # ### end Alembic commands ###
