"""Fix foreign keys sender_id and receiver_id to String(36)

Revision ID: d954849e7ee9
Revises: 6d7696d80f32
Create Date: 2025-07-22 15:21:34.362913

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d954849e7ee9"
down_revision = "6d7696d80f32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.alter_column(
            "sender_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "receiver_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.alter_column(
            "receiver_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "sender_id",
            existing_type=sa.String(length=36),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
